name: Actualizar Widget Diario

on:
  schedule:
    - cron: '0 00 * * *'  # Todos los días a las 00:00 AM 
  workflow_dispatch:      # Ejecución manual desde GitHub

jobs:
  update-widget:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Ejecutar script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        run: node quote-widget.js
